inherit_from: .rubocop_todo.yml

Layout/FirstHashElementIndentation:
   Enabled: false

Metrics/MethodLength:
   Enabled: false

Metrics/ClassLength:
   Enabled: false

Style/Documentation:
   Enabled: false

Naming/PredicatePrefix:
   Enabled: false

plugins:
  - rubocop-sorbet
